# Generated by Django 6.0.5 on 2026-06-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_incident_dispatcher_email_incident_dispatcher_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='barangay',
            field=models.CharField(blank=True, max_length=120, verbose_name='Sitio / Purok / Landmark'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='municipality',
            field=models.CharField(choices=[('Bagong Lipunan', 'Bagong Lipunan'), ('Balilit', 'Balilit'), ('Barayong', 'Barayong'), ('Barugohay Central', 'Barugohay Central'), ('Barugohay Norte', 'Barugohay Norte'), ('Barugohay Sur', 'Barugohay Sur'), ('Baybay', 'Baybay'), ('Binibihan', 'Binibihan'), ('Bislig', 'Bislig'), ('Caghalo', 'Caghalo'), ('Camansi', 'Camansi'), ('Canal', 'Canal'), ('Candigahub', 'Candigahub'), ('Canfabi', 'Canfabi'), ('Canlampay', 'Canlampay'), ('Cogon', 'Cogon'), ('Cutay', 'Cutay'), ('East Visoria', 'East Visoria'), ('Guindapunan East', 'Guindapunan East'), ('Guindapunan West', 'Guindapunan West'), ('Hiluctogan', 'Hiluctogan'), ('Jugaban', 'Jugaban'), ('Libo', 'Libo'), ('Lower Hiraan', 'Lower Hiraan'), ('Lower Sogod', 'Lower Sogod'), ('Macalpi', 'Macalpi'), ('Manloy', 'Manloy'), ('Nauguisan', 'Nauguisan'), ('Paglaum', 'Paglaum'), ('Pangna', 'Pangna'), ('Parag-um', 'Parag-um'), ('Parina', 'Parina'), ('Piloro', 'Piloro'), ('Ponong', 'Ponong'), ('Rizal', 'Rizal'), ('Sagkahan', 'Sagkahan'), ('San Isidro', 'San Isidro'), ('San Juan', 'San Juan'), ('San Mateo', 'San Mateo'), ('Santa Fe', 'Santa Fe'), ('Sawang', 'Sawang'), ('Tagak', 'Tagak'), ('Tangnan', 'Tangnan'), ('Tigbao', 'Tigbao'), ('Tinaguban', 'Tinaguban'), ('Upper Hiraan', 'Upper Hiraan'), ('Upper Sogod', 'Upper Sogod'), ('Uyawan', 'Uyawan'), ('West Visoria', 'West Visoria')], max_length=120, verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='barangay',
            field=models.CharField(blank=True, max_length=120, verbose_name='Sitio / Purok / Landmark'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='municipality',
            field=models.CharField(choices=[('Bagong Lipunan', 'Bagong Lipunan'), ('Balilit', 'Balilit'), ('Barayong', 'Barayong'), ('Barugohay Central', 'Barugohay Central'), ('Barugohay Norte', 'Barugohay Norte'), ('Barugohay Sur', 'Barugohay Sur'), ('Baybay', 'Baybay'), ('Binibihan', 'Binibihan'), ('Bislig', 'Bislig'), ('Caghalo', 'Caghalo'), ('Camansi', 'Camansi'), ('Canal', 'Canal'), ('Candigahub', 'Candigahub'), ('Canfabi', 'Canfabi'), ('Canlampay', 'Canlampay'), ('Cogon', 'Cogon'), ('Cutay', 'Cutay'), ('East Visoria', 'East Visoria'), ('Guindapunan East', 'Guindapunan East'), ('Guindapunan West', 'Guindapunan West'), ('Hiluctogan', 'Hiluctogan'), ('Jugaban', 'Jugaban'), ('Libo', 'Libo'), ('Lower Hiraan', 'Lower Hiraan'), ('Lower Sogod', 'Lower Sogod'), ('Macalpi', 'Macalpi'), ('Manloy', 'Manloy'), ('Nauguisan', 'Nauguisan'), ('Paglaum', 'Paglaum'), ('Pangna', 'Pangna'), ('Parag-um', 'Parag-um'), ('Parina', 'Parina'), ('Piloro', 'Piloro'), ('Ponong', 'Ponong'), ('Rizal', 'Rizal'), ('Sagkahan', 'Sagkahan'), ('San Isidro', 'San Isidro'), ('San Juan', 'San Juan'), ('San Mateo', 'San Mateo'), ('Santa Fe', 'Santa Fe'), ('Sawang', 'Sawang'), ('Tagak', 'Tagak'), ('Tangnan', 'Tangnan'), ('Tigbao', 'Tigbao'), ('Tinaguban', 'Tinaguban'), ('Upper Hiraan', 'Upper Hiraan'), ('Upper Sogod', 'Upper Sogod'), ('Uyawan', 'Uyawan'), ('West Visoria', 'West Visoria')], max_length=120, verbose_name='Barangay'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='municipalities',
            field=models.JSONField(default=list, verbose_name='Barangays affected'),
        ),
    ]
