# Generated by Django 6.0.5 on 2026-06-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='municipality',
            field=models.CharField(blank=True, max_length=120, verbose_name='Barangay'),
        ),
    ]
